# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  booksread:
    output: true
    title: Books Read

  futurereads:
    output: true
    title: Upcoming Reads

